article_list = [
        {
            "id":"1",
            "content": "In this tutorial you will make your first Java app. I assume that you have already installed the JDK as described here: Installing the Java SDK In this tutorial I will show you how to make your first Java app with IntelliJ IDEA community edition (free) version 2019.3.3. If you are using a different version of IDEA, or you are using Eclipse, Netbeans, or some other editor or IDE, things may look different from what I show you here. The article about installing the Java SDK also contains links to these Java IDEs.If you are completely new to Java there will be many concepts you don't understand in this article. Don't worry. Later articles will explain these concepts. The purpose of this article is just to get a working Java program running, so you can make changes to it yourself, as you read the later texts in this tutorial trail.Start IntelliJ IDEA First you have to start IntelliJ IDEA. How you do that depends on what operating system you are running (Windows, Mac, Linux etc.)When IntelliJ IDEA is running you will see the IntelliJ IDEA app window which looks like this:",
            "categories": ["java", "intellij"]
        },
        {
            "id": "2",
            "content": "In this tutorial you will make your first Java app. I assume that you have already installed the JDK as described here: Installing the Java SDK In this tutorial I will show you how to make your first Java app with IntelliJ IDEA community edition (free) version 2019.3.3. If you are using a different version of IDEA, or you are using Eclipse, Netbeans, or some other editor or IDE, things may look different from what I show you here. The article about installing the Java SDK also contains links to these Java IDEs.If you are completely new to Java there will be many concepts you don't understand in this article. Don't worry. Later articles will explain these concepts. The purpose of this article is just to get a working Java program running, so you can make changes to it yourself, as you read the later texts in this tutorial trail.Start IntelliJ IDEA First you have to start IntelliJ IDEA. How you do that depends on what operating system you are running (Windows, Mac, Linux etc.)When IntelliJ IDEA is running you will see the IntelliJ IDEA app window which looks like this:",
            "categories": ["java", "productivity"]
        },
        {
            "id": "3",
            "content": "In this tutorial you will make your first Java app. I assume that you have already installed the JDK as described here: Installing the Java SDK In this tutorial I will show you how to make your first Java app with IntelliJ IDEA community edition (free) version 2019.3.3. If you are using a different version of IDEA, or you are using Eclipse, Netbeans, or some other editor or IDE, things may look different from what I show you here. The article about installing the Java SDK also contains links to these Java IDEs.If you are completely new to Java there will be many concepts you don't understand in this article. Don't worry. Later articles will explain these concepts. The purpose of this article is just to get a working Java program running, so you can make changes to it yourself, as you read the later texts in this tutorial trail.Start IntelliJ IDEA First you have to start IntelliJ IDEA. How you do that depends on what operating system you are running (Windows, Mac, Linux etc.)When IntelliJ IDEA is running you will see the IntelliJ IDEA app window which looks like this:",
            "categories": ["IDE setup"]
        },
        {
            "id": "4",
            "content": "In this tutorial you will make your first Java app. I assume that you have already installed the JDK as described here: Installing the Java SDK In this tutorial I will show you how to make your first Java app with IntelliJ IDEA community edition (free) version 2019.3.3. If you are using a different version of IDEA, or you are using Eclipse, Netbeans, or some other editor or IDE, things may look different from what I show you here. The article about installing the Java SDK also contains links to these Java IDEs.If you are completely new to Java there will be many concepts you don't understand in this article. Don't worry. Later articles will explain these concepts. The purpose of this article is just to get a working Java program running, so you can make changes to it yourself, as you read the later texts in this tutorial trail.Start IntelliJ IDEA First you have to start IntelliJ IDEA. How you do that depends on what operating system you are running (Windows, Mac, Linux etc.)When IntelliJ IDEA is running you will see the IntelliJ IDEA app window which looks like this:",
            "categories": ["JavaEE"]
        },
        {
            "id": "5",
            "content": "In this tutorial you will make your first Java app. I assume that you have already installed the JDK as described here: Installing the Java SDK In this tutorial I will show you how to make your first Java app with IntelliJ IDEA community edition (free) version 2019.3.3. If you are using a different version of IDEA, or you are using Eclipse, Netbeans, or some other editor or IDE, things may look different from what I show you here. The article about installing the Java SDK also contains links to these Java IDEs.If you are completely new to Java there will be many concepts you don't understand in this article. Don't worry. Later articles will explain these concepts. The purpose of this article is just to get a working Java program running, so you can make changes to it yourself, as you read the later texts in this tutorial trail.Start IntelliJ IDEA First you have to start IntelliJ IDEA. How you do that depends on what operating system you are running (Windows, Mac, Linux etc.)When IntelliJ IDEA is running you will see the IntelliJ IDEA app window which looks like this:",
            "categories": ["stupidity"]
        },
        {
            "id": "6",
            "content": "In this tutorial you will make your first Java app. I assume that you have already installed the JDK as described here: Installing the Java SDK In this tutorial I will show you how to make your first Java app with IntelliJ IDEA community edition (free) version 2019.3.3. If you are using a different version of IDEA, or you are using Eclipse, Netbeans, or some other editor or IDE, things may look different from what I show you here. The article about installing the Java SDK also contains links to these Java IDEs.If you are completely new to Java there will be many concepts you don't understand in this article. Don't worry. Later articles will explain these concepts. The purpose of this article is just to get a working Java program running, so you can make changes to it yourself, as you read the later texts in this tutorial trail.Start IntelliJ IDEA First you have to start IntelliJ IDEA. How you do that depends on what operating system you are running (Windows, Mac, Linux etc.)When IntelliJ IDEA is running you will see the IntelliJ IDEA app window which looks like this:",
            "categories": ["cool"]
        }

    ]
